//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTak.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventOrganizer
    {
        public int Id { get; set; }
        public Nullable<int> OrganizerId { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
